In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [7]:
#df=pd.read_csv('GabHateCorpus_full_predictions.csv')

In [8]:
#df.head()

In [9]:
df2=pd.read_csv('data/GabHateCorpus_annotations.tsv', sep='\t')

In [10]:
df2.head()

ID  Annotator                                               Text  Hate  \
0  27044          4  Ah the PSYOPS antifa crew is back. That’s how ...     0   
1  27044         15  Ah the PSYOPS antifa crew is back. That’s how ...     0   
2  27044         10  Ah the PSYOPS antifa crew is back. That’s how ...     0   
3  27044          8  Ah the PSYOPS antifa crew is back. That’s how ...     0   
4  27045          4  Get the new Android app update released today ...     0   

   HD  CV  VO  REL  RAE  SXO  GEN  IDL  NAT  POL  MPH  EX  IM  
0   0   0   0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN NaN NaN  
1   0   0   0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN NaN NaN  
2   0   0   0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN NaN NaN  
3   0   0   0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN NaN NaN  
4   0   0   0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN NaN NaN

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
document_tfidf_matrix = vectorizer.fit_transform(df2['Text'])

/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [12]:
len(vectorizer.vocabulary_)

42969

In [13]:
#print(sorted(vectorizer.vocabulary_))
print(document_tfidf_matrix.todense())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [14]:
type(document_tfidf_matrix)

scipy.sparse.csr.csr_matrix

In [15]:
#document_tfidf_matrix = document_tfidf_matrix.toarray()

In [16]:
type(document_tfidf_matrix)

scipy.sparse.csr.csr_matrix

In [17]:
document_tfidf_matrix.shape

(86529, 42969)

In [18]:
words = vectorizer.get_feature_names()
words[-10:]

['𝕷𝖎𝖘𝖙𝖊𝖓𝖎𝖓𝖌',
 '𝕹𝖎𝖇𝖊𝖑𝖚𝖓𝖌𝖊𝖓',
 '𝕺𝖋',
 '𝕽𝖎𝖓𝖌',
 '𝕿𝖍𝖊',
 '𝕿𝖎𝖒𝖊',
 '𝕿𝖔',
 '𝖉𝖊𝖘',
 '𝙽𝚊𝚛𝚛𝚊𝚝𝚒𝚟𝚎',
 '𝟏𝐬𝐭']

In [19]:
#plt.figure(figsize=(20,4))
#_ = plt.imshow(document_tfidf_matrix[:,200:600])

In [20]:
X = document_tfidf_matrix
y = df2['Hate']

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [22]:
model = LogisticRegression().fit(X_train, y_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [23]:
model.predict_proba(X_test)

array([[0.89635272, 0.10364728],
       [0.63944884, 0.36055116],
       [0.81784325, 0.18215675],
       ...,
       [0.97620837, 0.02379163],
       [0.95909218, 0.04090782],
       [0.93583637, 0.06416363]])

In [24]:
coef = model.coef_.reshape(-1)

In [31]:
y_predict = [int(p[1] > 0.5) for p in model.predict_proba(X_test)]

In [27]:
coef[0]

-0.28662131128002827

In [28]:
words = np.array(words)
idx = np.argsort(coef)[-10:]
words[idx]

array(['libtard', 'islam', 'white', 'muslims', 'jews', 'muslim', 'faggot',
       'jew', 'niggers', 'nigger'], dtype='<U217')

In [32]:
accuracy_score(y_test, y_predict)

0.8730498093146886